services:
  django-collector-service:
    build: .
    container_name: django-collector-container
    volumes:
      - .:/django_collector_project
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgresql_collector
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - DB_HOST=postgresql-collector-service
      - DB_PORT=5432
    depends_on:
      postgresql-collector-service:
        condition: service_healthy
  
  postgresql-collector-service:
    image: postgres:13
    container_name: postgresql-collector-container
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgresql_collector
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres_user", "-d", "postgresql_collector"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: shared_network
    external: true