# Generated by Django 5.1.4 on 2024-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_id', models.IntegerField()),
                ('page_name', models.CharField(max_length=255)),
                ('average_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MostViewedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_id', models.IntegerField()),
                ('page_name', models.CharField(max_length=255)),
                ('sum_of_viewed', models.FloatField()),
            ],
        ),
    ]
