# Generated by Django 5.1.4 on 2024-12-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagetime',
            name='special_id',
        ),
        migrations.RemoveField(
            model_name='mostviewedpage',
            name='special_id',
        ),
    ]
