name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Test Django Collector
        working-directory: ./django_collector
        run: |
          docker-compose up -d
          docker exec -i django-collector-container python manage.py test
          docker-compose down
      
      - name: Test Django Processor
        working_directory: ./django_processor
        run: |
          docker-compose up -d
          docker exec -i processor-django-container python manage.py test
          docker-compose down
      
      - name: Test Django API
        working_directory: ./django_api
        run: |
          docker-compose up -d
          docker exec -i django-api-container python manage.py test
          docker-compose down